### PR TITLE
fix: include reuse libs for Launchpad #36

### LINKED ISSUE #36: Generated FlpSandbox shows an empty page
## Easy-Ui5 version:
3.3.0

## OS/version:
Windows 10 (Node.js version 14.19.0 and 16.14.0)

## Browser/version (+device/version):
Mozilla Firefox 97.0.1 (also MS Edge)

## Steps to reproduce the problem:
Follow [this](https://developers.sap.com/tutorials/sapui5-fiori-cf-create-project.html) tutorial

1. Step 1
run `yo easy-ui5 project`
2. Step 2
Select _SAP Launchpad service_ as hosting platform
3. Step 3
run `npm start`

## What is the expected result?
Flp should show up in browser, with the application tile

## What happens instead?
An empty page is displayed

## Any other information? (attach screenshot if possible)
Generated flpSandbox.html

```
<!DOCTYPE HTML>
<html>
<!-- Copyright (c) 2015 SAP AG, All Rights Reserved -->
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{appTitle}}</title>

    <!-- Bootstrap the unified shell in sandbox mode for standalone usage.

         The renderer is specified in the global Unified Shell configuration object "sap-ushell-config".

         The fiori2 renderer will render the shell header allowing, for instance,
         testing of additional application setting buttons.

         The navigation target resolution service is configured in a way that the empty URL hash is
         resolved to our own application.

         This example uses relative path references for the SAPUI5 resources and test-resources;
         it might be necessary to adapt them depending on the target runtime platform.
         The sandbox platform is restricted to development or demo use cases and must NOT be used
         for productive scenarios.
    -->
    <script type="text/javascript">
        window["sap-ushell-config"] = {
            defaultRenderer: "fiori2",
            bootstrapPlugins: {
                "RuntimeAuthoringPlugin": {
                    component: "sap.ushell.plugins.rta",
                    config: {
                        validateAppVersion: false
                    }
                }
            },
            renderers: {
                fiori2: {
                    componentData: {
                        config: {
                            search: "hidden"
                        }
                    }
                }
            },
            applications: {
                "comexamplenwProduct-tile": {
                    title: "Title of com.example.nwProduct",
                    description: "Description of com.example.nwProduct",
                    additionalInformation: "SAPUI5.Component=com.example.nwProduct",
                    applicationType: "URL",
                    url: "../"
                }
            }
        };
    </script>

    <script src="https://sapui5.hana.ondemand.com/test-resources/sap/ushell/bootstrap/sandbox.js" id="sap-ushell-bootstrap"></script>
    <!-- Bootstrap the UI5 core library -->
    <script id="sap-ui-bootstrap"
        src="https://sapui5.hana.ondemand.com/resources/sap-ui-core.js"
        data-sap-ui-libs="sap.m,sap.ui.core"
        data-sap-ui-async="true"
        data-sap-ui-preload="async"
        data-sap-ui-theme="sap_fiori_3"
        data-sap-ui-compatVersion="edge"
        data-sap-ui-language="en"
        data-sap-ui-resourceroots='{"com.example.nwProduct": "../"}'
        data-sap-ui-frameOptions="allow"> // NON-SECURE setting for testing environment
        </script>
</head>

<!-- UI Content -->

<body class="sapUiBody" id="content">
</body>

</html>

```

Console output:
immagine

### PR DESCRIPTION
**Pull request by nicogeburek**
Looks like the [commit from last week](https://github.com/ui5-community/generator-ui5-project/pull/34/commits/dab1f704fc37b3daa7198b641c0e448c67bcb3b6) didn't do the job 100% (for #35), as we do need the reuse libs for the Fiori Launchpad. This fixes #36.

### CODE REVIEW

File: generators/newwebapp/index.js [hunk 1]
```diff
@@ -178,7 +178,7 @@ module.exports = class extends Generator {
                     }
                 },
                 appOptions: {
-                    loadReuseLibs: false
+                    loadReuseLibs: this.options.oneTimeConfig.platform === "SAP Launchpad service"
```
Comment (petermuessig) [inline generators/newwebapp/index.js:181]: personally I would prefer a constant since this String is used in 3 places in this file, would you mind to introduce a constant here @nicogeburek ?

**Review by petermuessig — CHANGES_REQUESTED** [review]

File: generators/newwebapp/index.js [hunk 2]
```diff
@@ -312,7 +313,7 @@ module.exports = class extends Generator {
                 const isUnneededXsApp =
                     sTarget.includes("xs-app") &&
                     !(
-                        this.options.oneTimeConfig.platform === "SAP Launchpad service" ||
+                        platformIsLaunchpad ||
                         this.options.oneTimeConfig.platform === "SAP HTML5 Application Repository service for SAP BTP"
```
Comment (petermuessig) [inline generators/newwebapp/index.js:317]: Sorry, @nicogeburek - but maybe you can make this also a const:

`this.options.oneTimeConfig.platform === "SAP HTML5 Application Repository service for SAP BTP"`

**Review by petermuessig — CHANGES_REQUESTED** [review]

File: generators/newwebapp/index.js (hunk 2 above)
Comment (nicogeburek) [reply generators/newwebapp/index.js]: Sure, no problem. I hope I caught them all this time 😄
